# You can override the included template(s) by including variable overrides
# See https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#priority-of-environment-variables
stages:
- test
sast:
  variables:
    SAST_EXCLUDED_PATHS: ".ci, .idea"
    SEARCH_MAX_DEPTH: '1'
    SAST_DEFAULT_ANALYZERS: gosec
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml
